on: push
name: Test FTP Deploy1
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action-Typescript@master
      with:
        ftp-server: ftp://47.241.17.161/
        ftp-username: ${{ secrets.ftpname }}
        ftp-password: ${{ secrets.ftppassword }}